name: mcMMO
version: "1.0"
main: org.adelio.mcMMO.McMMO
api-version: "1.21"

commands:
  mcmmo:
    description: "mcMMO 관리자 전용 명령어 (셋팅 및 초기화)"
    permission: op
    usage: "/mcmmo <set/reset> <플레이어> <스킬/포인트> [값]"
  stats:
    description: "본인의 mcmmo 스탯 정보를 GUI 창으로 확인합니다."
    usage: "/stats"

permissions:
  mcmmo.admin:
    description: "관리자 명령어를 사용할 수 있는 권한"
    default: op